{
 "title": "MM2 - Dashboard - v2",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "MirrorMaker metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Task running ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "min by (host,connector,task) (min_over_time(kafka_connect:connector_task_metrics_running_ratio{project='your-aiven-project-name',service=~'your-aiven-mm2-service-name'}[$__interval]))",
     "legendFormat": "{{replication_flow}}"
    }
   ]
  },
  {
   "title": "Byte Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum without (host,partition) (avg_over_time(kafka_connect_mirror:MirrorSourceConnector_byte_rate{project='your-aiven-project-name',service=~'your-aiven-mm2-service-name'}[$__interval]))",
     "legendFormat": "{{target}} - {{topic}}"
    }
   ]
  },
  {
   "title": "Total Byte Rate - Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (topic) (avg_over_time(kafka_connect_mirror:MirrorSourceConnector_byte_rate{project='your-aiven-project-name',service=~'your-aiven-mm2-service-name'}[$__interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Record Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum without (host,partition) (avg_over_time(kafka_connect_mirror:MirrorSourceConnector_record_rate{project='your-aiven-project-name',service=~'your-aiven-mm2-service-name'}[$__interval]))",
     "legendFormat": "{{target}} - {{topic}}"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "timeseries",
   "description": "The total replication lag per replication flow",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (replication_flow) (sum by (replication_flow, host) (avg_over_time(kafka_mirrormaker_summary_replication_lag{project='your-aiven-project-name',service=~'your-aiven-mm2-service-name'}[$__interval])))",
     "legendFormat": "{{replication_flow}}"
    }
   ]
  },
  {
   "title": "Replication Latnecy",
   "type": "timeseries",
   "description": "Time it takes records to replicate from source to target cluster. The difference between the current moment and record timestamp when the record is committed to the target cluster. \n\nlong latency = System.currentTimeMillis() - record.timestamp();",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max without (host,partition) (max_over_time(kafka_connect_mirror:MirrorSourceConnector_replication_latency_ms{project='your-aiven-project-name',service=~'your-aiven-mm2-service-name'}[$__interval]))",
     "legendFormat": "{{target}}-{{topic}}"
    }
   ]
  },
  {
   "title": "Checkpoint Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (group, topic , value, host) (avg_over_time(kafka_connect_mirror:MirrorCheckpointConnector_checkpoint_latency_ms{service_id=~'$service_id'}[$__interval]))",
     "legendFormat": "{{topic}}-{{group}}"
    }
   ]
  },
  {
   "title": "Record Rate - PER TOPIC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (topic) (avg_over_time(kafka_connect_mirror:MirrorSourceConnector_record_rate{project='your-aiven-project-name',service=~'your-aiven-mm2-service-name'}[$__interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Connect Restarts by 5m intervals",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (host) (changes(kafka_connect:app_info_StartTimeMs{project='your-aiven-project-name',service=~'your-aiven-mm2-service-name'}[5m]))"
    }
   ]
  },
  {
   "title": "Task error/failure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (host, connector, task) (max_over_time(kafka_connect:task_error_metrics_total_record_failures{project='your-aiven-project-name',service=~'your-aiven-mm2-service-name'}[$__interval]))",
     "legendFormat": "{{ host }} - {{ connector }}.{{task}}"
    }
   ]
  },
  {
   "title": "Record age",
   "type": "barchart",
   "description": "The age of incoming source records when replicated to the target cluster. The difference between the current moment and record timestamp when the record is read by MirrorMaker.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by (host,topic) (max_over_time(kafka_connect_mirror:MirrorSourceConnector_record_age_ms{project='your-aiven-project-name',service=~'your-aiven-mm2-service-name'}[$__interval]))",
     "legendFormat": "{{host}} - {{topic}}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "max by (host)(kafka_connect:app_info_StartTimeMs{project='your-aiven-project-name',service=~'your-aiven-mm2-service-name'})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Task Running Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (host, connector, task) (max_over_time(kafka_connect:connector_task_metrics_running_ratio{project='your-aiven-project-name',service=~'your-aiven-mm2-service-name'}[$__interval]))",
     "legendFormat": "{{ host }} - {{ connector }}.{{task}}"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime (min)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(system_uptime{project='your-aiven-project-name',service='your-aiven-mm2-service-name'}[$__interval]))"
    }
   ]
  },
  {
   "title": "Load average (1 min max)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(system_load1{project='your-aiven-project-name',service='your-aiven-mm2-service-name'}[$__interval])) "
    }
   ]
  },
  {
   "title": "Memory available (min)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(mem_available{project='your-aiven-project-name',service='your-aiven-mm2-service-name'}[$__interval])) "
    }
   ]
  },
  {
   "title": "System metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (host)(avg_over_time(cpu_usage_system{project='your-aiven-project-name',service='your-aiven-mm2-service-name'}[$__interval])) ",
     "legendFormat": "{{ host }}.system"
    },
    {
     "expr": "avg by (host)(avg_over_time(cpu_usage_iowait{project='your-aiven-project-name',service='your-aiven-mm2-service-name'}[$__interval]))",
     "legendFormat": "{{host}}.iowait"
    },
    {
     "expr": "avg by (host)(avg_over_time(cpu_usage_irq{project='your-aiven-project-name',service='your-aiven-mm2-service-name'}[$__interval]))",
     "legendFormat": "{{host}}.irq"
    },
    {
     "expr": "avg by (host)(avg_over_time(cpu_usage_user{project='your-aiven-project-name',service='your-aiven-mm2-service-name'}[$__interval]))",
     "legendFormat": "{{host}}.user"
    }
   ]
  },
  {
   "title": "Load average (1 min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 34 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max by (host)(max_over_time(system_load1{project='your-aiven-project-name',service='your-aiven-mm2-service-name'}[$__interval])) ",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Memory available",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "min by (host)(min_over_time(mem_available{project='your-aiven-project-name',service='your-aiven-mm2-service-name'}[$__interval]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Memory unused",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (host)(avg_over_time(mem_free{project='your-aiven-project-name',service='your-aiven-mm2-service-name'}[$__interval]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Context switches",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg by (host)(rate(kernel_context_switches{project='your-aiven-project-name',service='your-aiven-mm2-service-name'}[$__rate_interval]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 40 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "min by (host)(rate(kernel_interrupts{project='your-aiven-project-name',service='your-aiven-mm2-service-name'}[$__rate_interval])) ",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg by (host)(avg_over_time(processes_blocked{project='your-aiven-project-name',service='your-aiven-mm2-service-name'}[$__interval]))",
     "legendFormat": "blocked.{{host}}"
    },
    {
     "expr": "avg by (host)(avg_over_time(processes_paging{project='your-aiven-project-name',service='your-aiven-mm2-service-name'}[$__interval]))",
     "legendFormat": "paging.{{host}}"
    },
    {
     "expr": "avg by (host)(avg_over_time(processes_running{project='your-aiven-project-name',service='your-aiven-mm2-service-name'}[$__interval]))",
     "legendFormat": "running.{{host}}"
    },
    {
     "expr": "avg by (host)(avg_over_time(processes_zombies{project='your-aiven-project-name',service='your-aiven-mm2-service-name'}[$__interval]))",
     "legendFormat": "zombies.{{host}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg by (host)(rate(net_bytes_recv{project='your-aiven-project-name',service='your-aiven-mm2-service-name'}[$__rate_interval])) ",
     "legendFormat": "{{host}}.rx"
    },
    {
     "expr": "avg by (host)(rate(net_bytes_sent{project='your-aiven-project-name',service='your-aiven-mm2-service-name'}[$__rate_interval])) ",
     "legendFormat": "{{host}}.tx"
    }
   ]
  },
  {
   "title": "Network (sum of all nodes)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(net_bytes_recv{project='your-aiven-project-name',service='your-aiven-mm2-service-name'}[$__rate_interval])) ",
     "legendFormat": "rx"
    },
    {
     "expr": "sum(rate(net_bytes_sent{project='your-aiven-project-name',service='your-aiven-mm2-service-name'}[$__rate_interval])) ",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "TCP connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (host)(sum_over_time(netstat_tcp_established{project='your-aiven-project-name',service='your-aiven-mm2-service-name'}[$__interval]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "TCP socket state total on all nodes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU iowait",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 46 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (host)(avg_over_time(cpu_usage_iowait{project='your-aiven-project-name',service='your-aiven-mm2-service-name'}[$__interval])) ",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Java metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (host)(avg_over_time(java_lang:Memory_used{project='your-aiven-project-name',service='aiven-labs-dest-kafka-1'}[$__interval])) ",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Garbage collection count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 53 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg by (host)(rate(java_lang:GarbageCollector_G1_Young_Generation_CollectionCount{project='your-aiven-project-name',service='your-aiven-mm2-service-name'}[$__rate_interval]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Garbage collection duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by (host)(avg_over_time(java_lang:GarbageCollector_G1_Young_Generation_CollectionTime{project='your-aiven-project-name',service='your-aiven-mm2-service-name'}[$__interval])) ",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}