{
 "title": "Kafka Custom Metrics Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "query_result(cpu_usage_idle{service_type=\"kafka\"})"
    }
   },
   {
    "name": "project",
    "query": {
     "query": "query_result(cpu_usage_idle{service=~\"$service\"})"
    }
   },
   { "name": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime (min)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(system_uptime{project='$project',service='$service'}[$__interval])) "
    }
   ]
  },
  {
   "title": "Load average (1 min max)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(system_load1{project='$project',service='$service'}[$__interval])) "
    }
   ]
  },
  {
   "title": "Memory available (min)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(mem_available{project='$project',service='$service'}[$__interval])) "
    }
   ]
  },
  {
   "title": "Disk free (min)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(disk_free{project='$project',service='$service'}[$__interval])) "
    }
   ]
  },
  {
   "title": "System metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (host)(avg_over_time(cpu_usage_system{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "{{ host }}.system"
    },
    {
     "expr": "avg by (host)(avg_over_time(cpu_usage_iowait{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "{{ host }}.iowait"
    },
    {
     "expr": "avg by (host)(avg_over_time(cpu_usage_irq{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "{{ host }}.irq"
    },
    {
     "expr": "avg by (host)(avg_over_time(cpu_usage_user{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "{{ host }}.user"
    }
   ]
  },
  {
   "title": "Load average (1 min)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (host)(max_over_time(system_load1{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Memory available",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "min by (host)(min_over_time(mem_available{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Memory unused",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (host)(avg_over_time(mem_free{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Context switches",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (host)(rate(kernel_context_switches{project='$project',service='$service'}[$__rate_interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "min by (host)(rate(kernel_interrupts{project='$project',service='$service'}[$__rate_interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (host)(avg_over_time(processes_blocked{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "blocked.{{ host }}"
    },
    {
     "expr": "avg by (host)(avg_over_time(processes_paging{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "paging.{{ host }}"
    },
    {
     "expr": "avg by (host)(avg_over_time(processes_running{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "running.{{ host }}"
    },
    {
     "expr": "avg by (host)(avg_over_time(processes_zombies{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "zombies.{{ host }}"
    }
   ]
  },
  {
   "title": "Disk free",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "min by (path,host)(min_over_time(disk_free{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "{{ host }}:{{ path }}"
    }
   ]
  },
  {
   "title": "Disk i/o",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg by (host)(rate(diskio_read_bytes{project='$project',service='$service'}[$__rate_interval])) ",
     "legendFormat": "{{ host }}.read"
    },
    {
     "expr": "avg by (host)(rate(diskio_write_bytes{project='$project',service='$service'}[$__rate_interval])) * -1",
     "legendFormat": "{{ host }}.write"
    }
   ]
  },
  {
   "title": "Data disk usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (path,host,path)(max_over_time(disk_used{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "CPU iowait",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (host)(avg_over_time(cpu_usage_iowait{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg by (host)(rate(net_bytes_recv{project='$project',service='$service'}[$__rate_interval])) ",
     "legendFormat": "{{ host }}.rx"
    },
    {
     "expr": "avg by (host)(rate(net_bytes_sent{project='$project',service='$service'}[$__rate_interval])) * -1",
     "legendFormat": "{{ host }}.tx"
    }
   ]
  },
  {
   "title": "Network (sum of all nodes)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(net_bytes_recv{project='$project',service='$service'}[$__rate_interval])) ",
     "legendFormat": "rx"
    },
    {
     "expr": "sum(rate(net_bytes_sent{project='$project',service='$service'}[$__rate_interval])) * -1",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "TCP connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (host)(sum_over_time(netstat_tcp_established{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "TCP socket state total on all nodes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(netstat_tcp_close{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "tcp_close"
    },
    {
     "expr": "sum(sum_over_time(netstat_tcp_close_wait{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "tcp_close_wait"
    },
    {
     "expr": "sum(sum_over_time(netstat_tcp_closing{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "tcp_closing"
    },
    {
     "expr": "sum(sum_over_time(netstat_tcp_established{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "tcp_established"
    },
    {
     "expr": "sum(sum_over_time(netstat_tcp_fin_wait1{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "tcp_fin_wait1"
    },
    {
     "expr": "sum(sum_over_time(netstat_tcp_fin_wait2{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "tcp_fin_wait2"
    },
    {
     "expr": "sum(sum_over_time(netstat_tcp_last_ack{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "tcp_last_ack"
    }
   ]
  },
  {
   "title": "Kafka metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Inbound messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "avg by (host)(rate(kafka_server_BrokerTopicMetrics_MessagesInPerSec_Count{project='$project',service='$service'}[$__rate_interval])) ",
     "legendFormat": "{{ host }}"
    },
    {
     "expr": "avg by (host)(rate(kafka_server:BrokerTopicMetrics_MessagesInPerSec_Count{project='$project',service='$service'}[$__rate_interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Fetch requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (host)(rate(kafka_network_RequestMetrics_RequestsPerSec_Count{project='$project',service='$service'}[$__rate_interval])) ",
     "legendFormat": "{{ host }}"
    },
    {
     "expr": "avg by (host)(rate(kafka_network:RequestMetrics_RequestsPerSec_Count{project='$project',service='$service'}[$__rate_interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Failed fetch requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "max by (host)(rate(kafka_server_BrokerTopicMetrics_FailedFetchRequestsPerSec_Count{project='$project',service='$service'}[$__rate_interval])) ",
     "legendFormat": "{{ host }}"
    },
    {
     "expr": "max by (host)(rate(kafka_server:BrokerTopicMetrics_FailedFetchRequestsPerSec_Count{project='$project',service='$service'}[$__rate_interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (host,request)(rate(kafka_network_RequestMetrics_RequestsPerSec_Count{project='$project',service='$service'}[$__rate_interval])) ",
     "legendFormat": "{{ host }}.{{ request }}"
    },
    {
     "expr": "avg by (host,request)(rate(kafka_network:RequestMetrics_RequestsPerSec_Count{project='$project',service='$service'}[$__rate_interval])) ",
     "legendFormat": "{{ host }}.{{ request }}"
    }
   ]
  },
  {
   "title": "Kafka log cleaner: time since last run",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (host)(avg_over_time(kafka_log_LogCleanerManager_time_since_last_run_ms_Value{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "{{ host }}"
    },
    {
     "expr": "avg by (host)(avg_over_time(kafka_log:LogCleanerManager_time_since_last_run_ms_Value{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Bytes in",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "max by (host)(rate(kafka_server_BrokerTopicMetrics_BytesInPerSec_Count{project='$project',service='$service'}[$__rate_interval])) ",
     "legendFormat": "{{ host }}"
    },
    {
     "expr": "max by (host)(rate(kafka_server:BrokerTopicMetrics_BytesInPerSec_Count{project='$project',service='$service'}[$__rate_interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Bytes out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "max by (host)(rate(kafka_server_BrokerTopicMetrics_BytesOutPerSec_Count{project='$project',service='$service'}[$__rate_interval])) ",
     "legendFormat": "{{ host }}"
    },
    {
     "expr": "max by (host)(rate(kafka_server:BrokerTopicMetrics_BytesOutPerSec_Count{project='$project',service='$service'}[$__rate_interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Underreplicated partitions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(max_over_time(kafka_server_ReplicaManager_UnderReplicatedPartitions_Value{project='$project',service='$service'}[$__interval])) "
    },
    {
     "expr": "max(max_over_time(kafka_server:ReplicaManager_UnderReplicatedPartitions_Value{project='$project',service='$service'}[$__interval])) "
    }
   ]
  },
  {
   "title": "Delayed operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (host,delayedoperation)(max_over_time(kafka_server_DelayedOperationPurgatory_NumDelayedOperations_Value{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "{{ host }}.{{ delayedOperation }}"
    },
    {
     "expr": "max by (host,delayedoperation)(max_over_time(kafka_server:DelayedOperationPurgatory_NumDelayedOperations_Value{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "{{ host }}.{{ delayedOperation }}"
    }
   ]
  },
  {
   "title": "Purgatory size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (host,delayedoperation)(max_over_time(kafka_server_DelayedOperationPurgatory_PurgatorySize_Value{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "{{ host }}.{{ delayedOperation }}"
    },
    {
     "expr": "max by (host,delayedoperation)(max_over_time(kafka_server:DelayedOperationPurgatory_PurgatorySize_Value{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "{{ host }}.{{ delayedOperation }}"
    }
   ]
  },
  {
   "title": "ISR expands",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "max by (host)(rate(kafka_server_ReplicaManager_IsrExpandsPerSec_Count{project='$project',service='$service'}[$__rate_interval])) ",
     "legendFormat": "{{ host }}"
    },
    {
     "expr": "max by (host)(rate(kafka_server:ReplicaManager_IsrExpandsPerSec_Count{project='$project',service='$service'}[$__rate_interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "ISR shrinks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "max by (host)(rate(kafka_server_ReplicaManager_IsrShrinksPerSec_Count{project='$project',service='$service'}[$__rate_interval])) ",
     "legendFormat": "{{ host }}"
    },
    {
     "expr": "max by (host)(rate(kafka_server:ReplicaManager_IsrShrinksPerSec_Count{project='$project',service='$service'}[$__rate_interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Handler threads idle",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (host)(avg_over_time(kafka_server_KafkaRequestHandlerPool_RequestHandlerAvgIdlePercent_OneMinuteRate{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "{{ host }}"
    },
    {
     "expr": "avg by (host)(avg_over_time(kafka_server:KafkaRequestHandlerPool_RequestHandlerAvgIdlePercent_OneMinuteRate{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Network threads idle",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (host)(avg_over_time(kafka_network_SocketServer_NetworkProcessorAvgIdlePercent_Value{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "{{ host }}"
    },
    {
     "expr": "avg by (host)(avg_over_time(kafka_network:SocketServer_NetworkProcessorAvgIdlePercent_Value{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Leader election rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (host)(rate(kafka_controller_ControllerStats_LeaderElectionRateAndTimeMs_Count{project='$project',service='$service'}[$__rate_interval])) ",
     "legendFormat": "{{ host }}"
    },
    {
     "expr": "avg by (host)(rate(kafka_controller:ControllerStats_LeaderElectionRateAndTimeMs_Count{project='$project',service='$service'}[$__rate_interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Unclean leader elections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (host)(rate(kafka_controller_ControllerStats_UncleanLeaderElectionsPerSec_Count{project='$project',service='$service'}[$__rate_interval])) ",
     "legendFormat": "{{ host }}"
    },
    {
     "expr": "avg by (host)(rate(kafka_controller:ControllerStats_UncleanLeaderElectionsPerSec_Count{project='$project',service='$service'}[$__rate_interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Consumer group lags",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (name)(avg_over_time(kafka_consumer_group_rep_lag{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  { "title": "Custom Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Partitions per Broker",
   "type": "timeseries",
   "description": "Number of partitions managed by a specific Kafka broker. This includes partitions for which the broker is the leader (responsible for handling client requests) and follower (which replicates data from the leader). \n\nNote: When you run a consumer application, a special system topic called __consumer_offsets will be created for Kafka to store consumer offsets. This topic will have 50 partitions. ",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "sum by (host)(max_over_time(kafka_server:ReplicaManager_PartitionCount_Value{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "{{ host }}"
    },
    {
     "expr": "sum by (host)(max_over_time(kafka_server_ReplicaManager_PartitionCount_Value{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 66 },
   "targets": [
    {
     "expr": "avg by (host,request)(rate(kafka_network_RequestMetrics_RequestsPerSec_Count{project='$project',service='$service'}[$__rate_interval])) ",
     "legendFormat": "{{ host }}.{{ request }}"
    }
   ]
  },
  {
   "title": "Kafka active controller count",
   "type": "timeseries",
   "description": "Number of active controllers in a Kafka cluster at any given time. In a healthy Kafka cluster, there should always be exactly one (1) active controller. ",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "min by (host)(kafka_controller_KafkaController_ActiveControllerCount_Value{project='$project',service='$service'})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "LeaderCount",
   "type": "timeseries",
   "description": "The number of partition leaders that a particular Kafka broker is currently managing. If one broker has a significantly higher leader count than others, it might experience higher CPU, memory, and network usage, potentially causing performance bottlenecks.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 66 },
   "targets": [
    {
     "expr": "avg by (host)(max_over_time(kafka_server_ReplicaManager_LeaderCount_Value{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Produce Requests",
   "type": "timeseries",
   "description": "The number of produce requests (i.e., write requests) per second that the Kafka broker is handling.\n\nTracking this metric over time helps you understand traffic patterns and plan capacity needs for the Kafka cluster.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg by (host)(rate(kafka_network_RequestMetrics_RequestsPerSec_Count{request='Produce',project='$project',service='$service'}[$__rate_interval]))",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Fetch requests - Total",
   "type": "timeseries",
   "description": "The number of fetch requests per second received by a Kafka broker. A fetch request is made by consumers (or follower brokers in the case of replication) to retrieve messages from Kafka topics. This metric is valuable for monitoring consumer activity and read traffic load on Kafka brokers.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(avg by (host)(rate(kafka_network_RequestMetrics_RequestsPerSec_Count{request='Fetch',project='$project',service='$service'}[$__rate_interval])))",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Conversions",
   "type": "timeseries",
   "description": "This metric tracks the rate of message format conversions that Kafka brokers perform per second during message production.\n\nA message format conversion occurs when the message format used by the producer differs from the message format that the Kafka broker is configured to store.\n\nHigh conversion rates might indicate that it’s time to upgrade your producers to the latest Kafka message format, reducing the conversion workload on brokers.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(kafka_server_BrokerTopicMetrics_ProduceMessageConversionsPerSec_Count{project='$project',service='$service'}[$__rate_interval])",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Dropped Connections",
   "type": "timeseries",
   "description": "The number of client connections to the Kafka broker that were unexpectedly dropped. Dropped connections can happen due to various reasons, including network instability, broker overload, timeouts, or client misconfiguration.\n\n",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 73 },
   "targets": [
    {
     "expr": "max by (host)(rate(service_connections_dropped{project='$project', service='$service'}[$__rate_interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "TCP Sockets: time_wait",
   "type": "timeseries",
   "description": "The number of TCP connections currently in the TIME_WAIT state on a system. This metric provides insight into the network health and connection management between Kafka brokers and clients (e.g., producers, consumers, or other brokers in the case of replication).",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "avg by (host)(avg_over_time(netstat_tcp_time_wait{project='$project', service='$service'}[$__interval])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TCP SYN Received",
   "type": "timeseries",
   "description": "The number of TCP connections currently in the SYN_RECV (SYN received) state. A high number of connections in the SYN_RECV state could indicate a backlog of pending connection requests, which may be caused by network issues, resource limitations, or excessive connection requests.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 80 },
   "targets": [
    {
     "expr": "avg by (host)(avg_over_time(netstat_tcp_syn_recv{project='$project',service='$service'}[$__interval]))",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "TCP SYN Sent",
   "type": "timeseries",
   "description": "Number of TCP connections currently in the SYN_SENT state on a system. \n\nHigh SYN_SENT counts may indicate network latency, connectivity issues, or issues with the remote service (e.g., other brokers or ZooKeeper not responding).\n\nA persistently high SYN_SENT count may also indicate that Kafka is attempting more outbound connections than usual, potentially due to retries or client misconfiguration.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 80 },
   "targets": [
    {
     "expr": "avg by (host)(avg_over_time(netstat_tcp_syn_sent{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "timeseries",
   "description": "Count of partitions that have no active brokers acting as their leader. Partitions become \"offline\" when none of their replicas are available, either due to broker failures, network issues, or other disruptions.\n\nA high or non-zero offline partition count often signals issues in the Kafka cluster, such as broker failures, replication issues, or network problems.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 80 },
   "targets": [
    {
     "expr": "avg by (host)(avg_over_time(kafka_controller_KafkaController_OfflinePartitionsCount_Value{project='$project',service='$service'}[$__interval])> 0) "
    }
   ]
  },
  {
   "title": "Swap Free",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "min by (host)(min_over_time(swap_free{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Swap In/Out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(rate(swap_in{project='$project', service='$service'}[$__rate_interval])) ",
     "legendFormat": "In (to memory)"
    },
    {
     "expr": "avg(rate(swap_out{project='$project', service='$service'}[$__rate_interval])) * -1",
     "legendFormat": "Out (to disk)"
    }
   ]
  },
  {
   "title": "Java metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (host)(avg_over_time(java_lang_Memory_used{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "{{ host }}"
    },
    {
     "expr": "avg by (host)(avg_over_time(java_lang:Memory_used{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Garbage collection count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (host)(rate(java_lang_GarbageCollector_G1_Young_Generation_CollectionCount{project='$project',service='$service'}[$__rate_interval])) ",
     "legendFormat": "{{ host }}"
    },
    {
     "expr": "avg by (host)(rate(java_lang:GarbageCollector_G1_Young_Generation_CollectionCount{project='$project',service='$service'}[$__rate_interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Garbage collection duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (host)(avg_over_time(java_lang_GarbageCollector_G1_Young_Generation_CollectionTime{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "{{ host }}"
    },
    {
     "expr": "avg by (host)(avg_over_time(java_lang:GarbageCollector_G1_Young_Generation_CollectionTime{project='$project',service='$service'}[$__interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  }
 ]
}