CREATE TABLE IF NOT EXISTS fake_orders (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    addr VARCHAR(100) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    user_agent TEXT NOT NULL,
    currency CHAR(3) NOT NULL,
    isbn CHAR(13) NOT NULL,
    qty INT NOT NULL,
    price NUMERIC(6,2) NOT NULL,
    created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);